#apiVersion: kubeadm.k8s.io/v1beta2
#kind: InitConfiguration
#localAPIEndpoint:
#  advertiseAddress: 10.136.21.110
#  bindPort: 6443
#---
#apiVersion: kubeadm.k8s.io/v1beta2
#kind: ClusterConfiguration
#kubernetesVersion: v1.16.0
#networking:
#  podSubnet: 10.244.0.0/16


apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.16.0
controlPlaneEndpoint: "10.136.21.110:6443"
networking:
  # This CIDR is a Calico default. Substitute or remove for your CNI provider.
  podSubnet: 10.244.0.0/16
#imageRepository: registry.cn-hangzhou.aliyuncs.com/imooc
